### ISSUE TITLE
[feature] 닉네임, 입장 코드 입력시 조건 걸기

### ISSUE THREAD

**Issue by oesnuj** [pknu-wap/WAG#378]
## 💥이슈 설명
현재 빈 닉네임이나 아래 사진과 같은 닉네임도 보내짐
![image](https://github.com/pknu-wap/WAG/assets/112786665/8880fe34-1770-47a8-9285-d85bff92229e)

## 📚할 일 목록
- [ ] 닉네임 입력 조건 명시
- [ ] 입장코드 입력시 처리

## 👀참고 사항
- 참고사항 작성

## ⌛기한
~

**Comment by wkdghdwns199** [comment]
https://github.com/pknu-wap/WAG/issues/397

여기서 닉네임 10자 제한 걸어서 구현했습니다.
